/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import java.util.List;
import java.util.ArrayList;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.DOMImplementation;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.transform.OutputKeys;
import javax.xml.transform.Result;
import javax.xml.transform.Source;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import modelo.Pelicula;

/**
 *
 * @author dieberalv
 */
public class Crear_XML_Peliculas extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Crear_XML_Peliculas.class.getName());

    // Lista para guardar las 9 películas antes de crear el archivo 
    private List<Pelicula> listaPeliculas = new ArrayList<>();

    // Creación de contadores para cumplir el límite de 3 películas por género 
    private int contadorMisterio = 0;
    private int contadorAventura = 0;
    private int contadorComedia = 0;

    public Crear_XML_Peliculas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        btnGenerarXML.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboGenero = new javax.swing.JComboBox<>();
        txtTitulo = new javax.swing.JTextField();
        btnAgregarPelicula = new javax.swing.JButton();
        txtURL = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnGenerarXML = new javax.swing.JButton();
        txtDuracion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Género:");

        jLabel2.setText("Título:");

        jLabel3.setText("Duración:");

        jLabel4.setText("Tráiler (URL):");

        comboGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Misterio", "Aventura", "Comedia" }));

        btnAgregarPelicula.setText("Agregar Película");
        btnAgregarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPeliculaActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        btnGenerarXML.setText("Generar XML");
        btnGenerarXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarXMLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtURL)
                            .addComponent(txtTitulo)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAgregarPelicula)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(btnGenerarXML)
                .addContainerGap(141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAgregarPelicula)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGenerarXML)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPeliculaActionPerformed
        try {
            // Obtener datos de la interfaz 
            String genero = (String) comboGenero.getSelectedItem();
            String titulo = txtTitulo.getText().trim();
            String duracionStr = txtDuracion.getText().trim();
            String url = txtURL.getText().trim();

            // Comprobar que el campo de título no está vacío 
            if (titulo.isEmpty()) {
                throw new Exception("El campo de título no puede estar vacío.");

            }

            // Comprobar que en el campo de duración se ha introducido un número positivo
            int duracion;
            try {
                duracion = Integer.parseInt(duracionStr);
                if (duracion <= 0) {
                    throw new NumberFormatException();
                }

            } catch (NumberFormatException e) {
                throw new Exception("La duración debe ser un número entero positivo (sin letras ni decimales).");

            }

            // Comprobar el formato de URL introducido
            if (!url.startsWith("http://") && !url.startsWith("https://")) {
                throw new Exception("Formato de URL introducido no válido. Debe comenzar por http:// o https://.");

            }

            // Establecer un límite de 3 películas por género 
            if (genero.equals("Misterio") && contadorMisterio >= 3) {
                throw new Exception("Ya hay 3 películas de Misterio.");
            }

            if (genero.equals("Aventura") && contadorAventura >= 3) {
                throw new Exception("Ya hay 3 películas de Aventura.");
            }

            if (genero.equals("Comedia") && contadorComedia >= 3) {
                throw new Exception("Ya hay 3 películas de Comedia.");
            }

            // Si todo es correcto, crear objeto y añadir a la lista
            Pelicula p = new Pelicula(titulo, duracion, url, genero);
            listaPeliculas.add(p);

            // Actualizar contadores y área de visualización 
            actualizarDatos(p, genero);

            // Condición para activar el botón de Generar XML 
            if (contadorMisterio == 3 && contadorAventura == 3 && contadorComedia == 3) {
                btnGenerarXML.setEnabled(true);

            }

            // Al final del "try", limpiar los elementos para que vuelvan a quedar vacíos
            txtTitulo.setText("");
            txtDuracion.setText("");
            txtURL.setText("");

        } catch (Exception e) {

            // Mensaje de error 
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_btnAgregarPeliculaActionPerformed

    private void btnGenerarXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarXMLActionPerformed

        try {
            // Crear el documento XML en memoria
            DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
            DocumentBuilder builder = factory.newDocumentBuilder();
            DOMImplementation implementation = builder.getDOMImplementation();
            Document documento = implementation.createDocument(null, "peliculas", null);
            documento.setXmlVersion("1.0");

            // Crear los nodos principales de género
            Element misterio = documento.createElement("misterio");
            Element aventura = documento.createElement("aventura");
            Element comedia = documento.createElement("comedia");

            // Clasificar y añadir las películas de la lista al XML
            for (Pelicula p : listaPeliculas) {
                // Crear el nodo película
                Element nodoPelicula = documento.createElement("pelicula");

                Element titulo = documento.createElement("titulo");
                titulo.setTextContent(p.getTitulo());
                nodoPelicula.appendChild(titulo);

                Element duracion = documento.createElement("duracion");
                duracion.setTextContent(String.valueOf(p.getDuracion()));
                nodoPelicula.appendChild(duracion);

                Element trailer = documento.createElement("trailer");
                trailer.setTextContent(p.getTrailer());
                nodoPelicula.appendChild(trailer);

                // Añadir al género correspondiente
                if (p.getGenero().equals("Misterio")) {
                    misterio.appendChild(nodoPelicula);
                } else if (p.getGenero().equals("Aventura")) {
                    aventura.appendChild(nodoPelicula);
                } else if (p.getGenero().equals("Comedia")) {
                    comedia.appendChild(nodoPelicula);
                }
            }

            // Unir géneros a la raíz
            documento.getDocumentElement().appendChild(misterio);
            documento.getDocumentElement().appendChild(aventura);
            documento.getDocumentElement().appendChild(comedia);

            // Guardar el archivo en el directorio del proyecto
            Source source = new DOMSource(documento);
            Result result = new StreamResult(new java.io.File("peliculas.xml"));
            Transformer transformer = TransformerFactory.newInstance().newTransformer();

            // Para que el XML sea legible
            transformer.setOutputProperty(OutputKeys.INDENT, "yes");
            transformer.transform(source, result);

            javax.swing.JOptionPane.showMessageDialog(this, "Archivo peliculas.xml generado con éxito.");

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al generar el XML: " + e.getMessage());
        }
    }//GEN-LAST:event_btnGenerarXMLActionPerformed

    private void actualizarDatos(Pelicula p, String genero) {
        if (genero.equals("Misterio")) {
            contadorMisterio++;
        } else if (genero.equals("Aventura")) {
            contadorAventura++;
        } else if (genero.equals("Comedia")) {
            contadorComedia++;
        }

        // Mostramos en el área de texto lo que vamos añadiendo [cite: 46]
        jTextArea1.append("Añadida: [" + genero + "] " + p.getTitulo() + "\n");
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Crear_XML_Peliculas dialog = new Crear_XML_Peliculas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPelicula;
    private javax.swing.JButton btnGenerarXML;
    private javax.swing.JComboBox<String> comboGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtURL;
    // End of variables declaration//GEN-END:variables
}
